# Generated by Django 5.1.15 on 2026-08-28 14:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("USER_LOGIN", "User Login"),
                            ("PROJECT_CREATED", "Project Created"),
                            ("PROJECT_UPDATED", "Project Updated"),
                            ("TASK_CREATED", "Task Created"),
                            ("TASK_UPDATED", "Task Updated"),
                            ("TASK_DELETED", "Task Deleted"),
                            ("MEMBER_ADDED", "Member Added"),
                            ("MEMBER_REMOVED", "Member Removed"),
                            ("ROLE_CHANGED", "Role Changed"),
                            ("SUBSCRIPTION_UPGRADED", "Subscription Upgraded"),
                            ("PAYMENT_SUCCESS", "Payment Success"),
                            ("INTEGRATION_SYNC", "Integration Synced"),
                            ("AUTOMATION_TRIGGERED", "Automation Rule Triggered"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField()),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
