# Generated by Django 5.1.15 on 2026-08-31 10:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_service_expense"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="expense",
            new_name="billing_exp_workspa_bea66f_idx",
            old_name="billing_exp_workspa_729481_idx",
        ),
        migrations.RenameIndex(
            model_name="expense",
            new_name="billing_exp_workspa_0bef6e_idx",
            old_name="billing_exp_workspa_18a22d_idx",
        ),
        migrations.AlterField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
