# Generated by Django 5.1.15 on 2026-08-31 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0003_rename_billing_exp_workspa_729481_idx_billing_exp_workspa_bea66f_idx_and_more",
        ),
        (
            "workspaces",
            "0003_rename_workspaces__workspa_202868_idx_workspaces__workspa_4fe607_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="workspaces.client",
            ),
        ),
    ]
