# Generated by Django 5.1.15 on 2026-08-28 14:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("TASK_STATUS_CHANGED", "When task status changes"),
                            ("TASK_CREATED", "When a new task is created"),
                            ("TASK_OVERDUE", "When a task becomes overdue"),
                            ("PR_OPENED", "When a Pull Request is opened"),
                            ("PR_MERGED", "When a Pull Request is merged"),
                        ],
                        max_length=40,
                    ),
                ),
                ("trigger_config", models.JSONField(blank=True, default=dict)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("MOVE_TASK_TO", "Move task to status"),
                            ("ASSIGN_TO_USER", "Assign to user"),
                            ("NOTIFY_ROLE", "Notify role (e.g. Lead Developer, PM)"),
                            ("SEND_WEBHOOK", "Trigger external webhook"),
                        ],
                        max_length=40,
                    ),
                ),
                ("action_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("execution_count", models.PositiveIntegerField(default=0)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="projects.project",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
