# Generated by Django 5.1.15 on 2026-08-31 10:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_client_lead"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="client",
            new_name="workspaces__workspa_4fe607_idx",
            old_name="workspaces__workspa_202868_idx",
        ),
        migrations.RenameIndex(
            model_name="client",
            new_name="workspaces__workspa_022f0e_idx",
            old_name="workspaces__workspa_5ff250_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="workspaces__workspa_5e4b62_idx",
            old_name="workspaces__workspa_78d8a7_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="workspaces__workspa_c396d5_idx",
            old_name="workspaces__workspa_2eaee3_idx",
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
