# Generated by Django 5.1.15 on 2026-08-28 14:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("TASK_DESCRIPTION", "Task Description Generation"),
                            ("IMPROVE_DESCRIPTION", "Improve Task Description"),
                            ("SUMMARIZE_PROJECT", "Project Summary"),
                            ("SUMMARIZE_SPRINT", "Sprint Summary & Retrospective"),
                            ("RELEASE_NOTES", "Release Notes Generation"),
                            ("ESTIMATE_COMPLEXITY", "Estimate Task Complexity"),
                            ("ANALYZE_OVERDUE", "Analyze Overdue Tasks"),
                        ],
                        max_length=40,
                    ),
                ),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                (
                    "model_name",
                    models.CharField(default="gemini-2.5-flash", max_length=50),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
